# Generated by Django 4.1 on 2023-01-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_date_created_product_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
