# Generated by Django 4.1 on 2023-01-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_tags_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('Cameroon', 'Cameroon'), ('Chad', 'Chad'), ('Nigeria', 'Nigeria'), ('Gabon', 'Gabon'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Central African Republic', 'Central African Republic'), ('Congo Republic', 'Congo Republic'), ('Democratic Republic of Congo', 'Democratic Republic of Congo'), ('Ghana', 'Ghana'), ('Togo', 'Togo'), ('Senegal', 'Senegal'), ('Guinea', 'Guinea')], default='Cameroon', max_length=50),
        ),
    ]
