# Generated by Django 4.1 on 2022-12-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phoneCountry',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
