# Generated by Django 4.1 on 2022-12-29 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phonecountry_profile_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='countryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneCountry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.countrycode'),
        ),
    ]
