# Generated by Django 4.1 on 2022-12-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_countrycode_alter_profile_phonecountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycode',
            name='country_abbr',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
