# Generated by Django 4.1 on 2022-12-30 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_address_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='CountryCode',
        ),
    ]
