# Generated by Django 4.1 on 2022-12-30 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryCode',
            new_name='Country',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('contry', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
            ],
        ),
    ]
