# Generated by Django 4.1 on 2022-12-30 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_countrycode_country_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='contry',
            new_name='country',
        ),
    ]
