# Generated by Django 4.1 on 2023-01-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phoneCountry',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='ProfileImages/'),
        ),
    ]
