# Generated by Django 4.1 on 2023-01-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phoneCountry',
            field=models.CharField(choices=[('cmr', '+237'), ('ngr', '+234'), ('fra', '+33'), ('Ger', '+49')], default='cmr', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
