# Generated by Django 4.1 on 2023-01-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_phonecountry_profile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneCountry',
            field=models.CharField(choices=[('+237', 'CMR'), ('+234', 'NGR'), ('+33', 'FRA'), ('+49', 'GER')], default='+237', max_length=5),
        ),
    ]
