# Generated by Django 4.1 on 2023-01-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_phonecountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneCountry',
            field=models.CharField(choices=[('+237', '+237 CMR'), ('+234', '+234 NGR'), ('+33', '+33 FRA'), ('+49', '+49 GER')], default='+237', max_length=5),
        ),
    ]
