# Generated by Django 4.1 on 2022-12-25 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('posts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.post')),
            ],
        ),
    ]
