# Generated by Django 4.1 on 2022-12-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Possible', max_length=255),
        ),
    ]
