# Generated by Django 4.1 on 2022-12-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_name_comment_body_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='name',
        ),
    ]
