# Generated by Django 4.1 on 2022-12-28 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_post_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='post_picture',
        ),
    ]
