# Generated by Django 4.1 on 2023-01-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='my_comment',
        ),
    ]
